pipeline {
    agent {
        label 'docker-agent-devsecops'
    }
    environment {
        REPO = "app2-flask"
        TAG   = "${BUILD_NUMBER}"
        PORT = "5050"
        DOCKERFILE = "shared-library/project-files/app2"
    }

    stages {
        stage('build') {
            steps {
                sh 'docker build -t "$REPO:$TAG" "$DOCKERFILE"'
            }
        }
        stage('deploy') {
            steps {
                sh 'docker rm -f $REPO || true'
                sh 'docker run -d --name $REPO -p "$PORT:$PORT" "$REPO:$TAG"'
            }
        }
    }
}
