pipeline {
    agent any
    environment {
        REPO = "app1-flask"
        TAG   = "${BUILD_NUMBER}"
        PORT = "5000"
        DOCKERFILE = "shared-library/project-files/app1"
    }

    stages {
        stage('build') {
            steps {
                sh 'docker build -t "$REPO:$TAG" "$DOCKERFILE"'
            }
        }
        stage('deploy') {
            steps {
                sh 'docker rm -f $REPO || true'
                sh 'docker run -d --name $REPO -p "$PORT:$PORT" "$REPO:$TAG"'
            }
        }
    }
}
